export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { JobDataProvider } from "@/contexts/JobDataContext"

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body><JobDataProvider>{children}</JobDataProvider></body>
    </html>
  )
}
